### ISSUE TITLE
What is the Significance of solid_cache over traditional one?

### ISSUE THREAD

**Issue by Anush-Kumar-S** [rails/solid_cache#220]
Team, traditional cache uses the memory. But solid cache is going to use database.

If database is used, then additional queries will be required to get and store the data.
And also why we should have new database for this. Won't it increase the maintenance cost? Why can't we use thew same application's database

**Comment by dhh** [comment]
From the opening paragraph of the README: "Solid Cache is a database-backed Active Support cache store that let's you keep a much larger cache than is typically possible with traditional memory-only Redis or Memcached stores. This is thanks to the speed of modern SSD drives, which make the access-time penalty of using disk vs RAM insignificant for most caching purposes. Simply put, you're now usually better off keeping a huge cache on disk rather than a small cache in memory."
